"""create_notifications_table

Revision ID: bb8819ae44fc
Revises: 
Create Date: 2026-07-09 16:59:43.359070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8819ae44fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Owning tenant — mandatory for all notifications.'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Target user. NULL = tenant-wide notification.'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Notification type — e.g. member_invited, new_reply.'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False, comment='False = unread, True = read.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC creation time.'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='UTC time when the notification was marked read.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_tenant_id', 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_tenant_read', 'notifications', ['tenant_id', 'read'], unique=False)
    op.create_index('ix_notifications_tenant_read_created', 'notifications', ['tenant_id', 'read', 'created_at'], unique=False)
    op.create_index('ix_notifications_tenant_user', 'notifications', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_tenant_user', table_name='notifications')
    op.drop_index('ix_notifications_tenant_read_created', table_name='notifications')
    op.drop_index('ix_notifications_tenant_read', table_name='notifications')
    op.drop_index('ix_notifications_tenant_id', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
